name: TA Exercise - Terraform / Ansible automation 
on: [ push ]    
jobs:
  # This first job is there to deploy the infrastructure with Terraform
  terraform-deployment:
    runs-on: ubuntu-latest
    steps: 
      - name: Authenticating with AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Clone your code in the pipeline
        uses: actions/checkout@v2

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_wrapper: false # this here is needed so that we can access the output ec2 instance public ip terraform output

      - name: Init
        id: init
        run: terraform init

      - name: Plan
        id: plan
        run: terraform plan
        continue-on-error: true

      - name: Apply
        id: apply
        run: terraform apply -auto-approve
        continue-on-error: true

      - name: Saving tf output
        run: 
          terraform output ec2_instance_ip >> new_public_ip_address

      - name: Updating inventory.hosts with new ip
        run:
          addr=`cat new_public_ip_address` && sed "s/ip_address_goes_here/$addr/" inventory.hosts > temp && mv temp inventory.hosts

      - name: Updating playbook_website with new ip
        run:
          addr=`cat new_public_ip_address` && sed "s/ip_address_goes_here/$addr/" playbook_website.yml > temp && mv temp playbook_website.yml

      # Below needs to be the steps for creating the website with ansible, as seen in the otheer repo

      - name: Running ansible
        run:
          ansible-playbook playbook_website.yml
